git:
  targetRevision: null

# stage: one of [dev, uat, prod]
stage: null

# network: one of [mainnet, preprod, preview]
network: null

# domain: something like "grafana.dev.ggargiulo-clusters.eu-west-1.metadata.dev.cf-deployments.org"
domain: null

# Infra Parameters
cf-summit-2023-infra:
  # Whether Infra resources should be deployed.
  enabled: true

# Ballot UI Parameters
cf-summit-2023-ui:
  # Whether Resources should be deployed.
  enabled: true

# Ballot API Parameters
cf-summit-2023-voting-api:
  # Whether Resources should be deployed.
  enabled: true

# Ballot Verification API Parameters
cf-summit-2023-verification-api:
  # Whether Resources should be deployed.
  enabled: true

# Ballot Ledger Follower API Parameters
cf-summit-2023-ledger-follower-api:
  # Whether Resources should be deployed.
  enabled: true

# Discord Wallet Verification
cf-discord-wallet-verification-bot:
  # Whether Resources should be deployed.
  enabled: true

grafana-dashboards:
  enabled: true

spec:
  destination:
    server: https://kubernetes.default.svc
